<a href='https://www.darshan.ac.in/'> <img src='https://www.darshan.ac.in/Content/media/DU_Logo.svg' width="250" height="300"/></a>
<pre>
<center><b><h1>Machine Learning - 2301CS621</b></center>

<center><b><h1>Lab - 1</b></center>    
<pre>    

# NumPy Exercises
## We'll start off with a few simple tasks

## import numpy as np

In [ ]:
import numpy as np

In [ ]:
arr =np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [ ]:
arr.dtype

dtype('int64')

## Create an array of 10 zeros

In [ ]:
arr = np.zeros([10,10])
print(arr)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


## Create an array of 10 ones

In [ ]:
arr = np.ones(10)
print(arr)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


## Create an array of 10 fives

In [ ]:
arr = np.ones(10)*5
print(arr)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## Create an array of the integers from 10 to 50

In [ ]:
arr = np.arange(10,51,2,int)
print(arr)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


## Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
arr = np.arange(9)
arr = arr.reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## Create a 3x3 identity matrix

In [ ]:
arr = np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Create following matrix  = <br/>
<pre>array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])</pre>

In [ ]:
arr = np.arange(1,26).reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

## Output should be =
<pre>array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])</pre>

In [ ]:
arr1 = arr[2:,1:]
arr1

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

## Output should be = <br/>
<pre>array([[ 2],
       [ 7],
       [12]])</pre>

In [ ]:
arr2 = arr[0:3, 1:2]
arr2

array([[ 2],
       [ 7],
       [12]])

## Find Odd Numbers
Extract all odd numbers from `arr`.

`arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])` <BR>
Use Condtional Selection

In [ ]:
arr = np.arange(10)
arr1 = arr[arr%2!=0]
arr1

array([1, 3, 5, 7, 9])

## Stacking
Stack array `a` and `b` vertically.

`a = np.arange(10).reshape(2,-1)`
`b = np.repeat(1, 10).reshape(2,-1)`

In [ ]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
arr1 = np.vstack([a,b])
arr1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

##  Range Filtering
Get all items between 5 and 10 from `a`.

`a = np.array([2, 6, 1, 9, 10, 3, 27])`

In [ ]:
a = np.array([2,6,1,9,10,3,27])
arr1 = a[(a>2) & (a<10)]
arr1

array([6, 9, 3])

## Matrix Multiplication
Multiply a 5x3 matrix by a 3x2 matrix (dot product).

In [ ]:
A = np.random.random((5,3))
B = np.random.random((3,2))


In [ ]:
arr1 = A.dot(B)
arr1

array([[1.44263568, 1.36170734],
       [0.69458084, 0.58077585],
       [0.94835896, 0.75401478],
       [1.43772012, 1.34313799],
       [1.06379961, 1.07230186]])

# Great Job! You’re Halfway Through 🚀  | PANDAS  Exercises

 **Context:** You are a Data Analyst at "TechCorp". 
HR has asked you to analyze employee data to understand attrition, salary trends, and job satisfaction.

**Instructions:**
1. Write your code in the empty cells.

### 1. Load & Inspect
Load `employee_data.csv` into a DataFrame named `df`. Display the first 5 rows and check column data types.

In [ ]:
import pandas as pd

df = pd.read_csv("employee_data.csv")
df.head()

EmployeeID  Age              Department            JobRole Attrition  \
0        1001   50  Research & Development     Data Scientist        No   
1        1002   36  Research & Development     Data Scientist        No   
2        1003   29                   Sales     Data Scientist        No   
3        1004   42                   Sales         Sales Exec        No   
4        1005   40                   Sales  Software Engineer        No   

   MonthlyIncome  YearsAtCompany  JobSatisfaction  PerformanceRating  \
0           8415              19                1                  4   
1           6391              19                3                  4   
2          14157              17                1                  4   
3          14835              13                3                  4   
4           8951              16                4                  3   

   PercentSalaryHike  DistanceFromHome MaritalStatus  
0                 16                20       Married  
1                 21                21       Married  
2                 22                18       Married  
3                 18                24       Married  
4                 22                27        Single

### 2. Filter IT Department
Create a DataFrame `df_rd` containing only employees from the `'Research & Development'` department.

In [ ]:
df_rd = df[df["Department"] == "Research & Development"]
df_rd.head()

EmployeeID  Age              Department         JobRole Attrition  \
0        1001   50  Research & Development  Data Scientist        No   
1        1002   36  Research & Development  Data Scientist        No   
5        1006   44  Research & Development      HR Manager       Yes   
6        1007   32  Research & Development  Data Scientist        No   
8        1009   45  Research & Development  Data Scientist        No   

   MonthlyIncome  YearsAtCompany  JobSatisfaction  PerformanceRating  \
0           8415              19                1                  4   
1           6391              19                3                  4   
5           8468               8                4                  3   
6          11007              19                2                  3   
8          12444               1                3                  3   

   PercentSalaryHike  DistanceFromHome MaritalStatus  
0                 16                20       Married  
1                 21                21       Married  
5                 12                11        Single  
6                 19                 2       Married  
8                 16                18       Married

### 3. Salary Check
Find the employee with the highest `MonthlyIncome`. Display their `JobRole` and `MonthlyIncome`.

In [ ]:
maxIncome = df["MonthlyIncome"].max()

df_rd = df[df["MonthlyIncome"] == maxIncome][['JobRole', 'MonthlyIncome']]
df_rd

JobRole  MonthlyIncome
28  HR Manager          14954

### 4. Missing Values
Check if there are any missing values (`NaN`) in the dataset.

In [ ]:
nanV = df.isna().sum()
nanV

EmployeeID           0
Age                  0
Department           0
JobRole              0
Attrition            0
MonthlyIncome        0
YearsAtCompany       0
JobSatisfaction      0
PerformanceRating    0
PercentSalaryHike    0
DistanceFromHome     0
MaritalStatus        0
dtype: int64

### 5. Average Age by Role
Calculate the average `Age` for each `JobRole`.

In [1]:
!nvidia-smi

Sat Dec  6 04:03:39 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   40C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [ ]:
df_rd = df.groupby('JobRole')
df_rd['Age'].mean()

JobRole
Data Scientist       38.771429
HR Manager           39.926829
Lab Technician       38.673469
Sales Exec           44.000000
Software Engineer    40.395349
Name: Age, dtype: float64

### 6. Attrition Count
How many employees have left the company? (Count values in the `Attrition` column).

In [ ]:
df['Attrition'].value_counts()['Yes']

np.int64(33)

### 7. High Performers
Filter for employees with `PercentSalaryHike` > 15 **AND** `PerformanceRating` == 4.

In [ ]:
df[(df['PercentSalaryHike'] > 3) & (df['PerformanceRating'] == 4)].head()

EmployeeID  Age              Department            JobRole Attrition  \
0         1001   50  Research & Development     Data Scientist        No   
1         1002   36  Research & Development     Data Scientist        No   
2         1003   29                   Sales     Data Scientist        No   
3         1004   42                   Sales         Sales Exec        No   
16        1017   59                   Sales  Software Engineer       Yes   

    MonthlyIncome  YearsAtCompany  JobSatisfaction  PerformanceRating  \
0            8415              19                1                  4   
1            6391              19                3                  4   
2           14157              17                1                  4   
3           14835              13                3                  4   
16          10577               6                2                  4   

    PercentSalaryHike  DistanceFromHome MaritalStatus  
0                  16                20       Married  
1                  21                21       Married  
2                  22                18       Married  
3                  18                24       Married  
16                 16                23      Divorced

### 8. Satisfaction Analysis (Pivot Table)
Create a pivot table showing the **average** `MonthlyIncome` for each `Department` (rows) broken down by `JobSatisfaction` (columns).

In [ ]:
plt = df.pivot_table(
    values='MonthlyIncome',
    index='Department',
    columns='JobSatisfaction',
    aggfunc=np.mean
)
plt

C:\Users\Dell\AppData\Local\Temp\ipykernel_15852\1788501515.py:1: FutureWarning: The provided callable <function mean at 0x00000121B6017100> is currently using DataFrameGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  satisfaction_analysis_pt = df.pivot_table(


JobSatisfaction                    1            2            3            4
Department                                                                 
Human Resources          8494.666667  8822.200000  8196.333333  7744.833333
Research & Development  10810.718750  8581.125000  8648.090909  8930.304348
Sales                    9795.789474  9590.461538  8459.461538  9045.000000

### 9. Feature Engineering (Seniority)
Create a new column `Seniority`.
* If `YearsAtCompany` > 10, value is `'Senior'`
* Otherwise, value is `'Junior'`

Count how many Seniors vs Juniors there are.

In [ ]:
df['Seniority'] = np.where(df['YearsAtCompany'] > 10, 'Senior', 'Junior')
df['Seniority'].head()

0    Senior
1    Senior
2    Senior
3    Senior
4    Senior
Name: Seniority, dtype: object

### 10. Retention Risk (Complex Filter)
Identify 'High Risk' employees who meet **ALL** these criteria:
1. `MaritalStatus` is 'Single'
2. `JobSatisfaction` is less than 3
3. `DistanceFromHome` > 10

Display their `EmployeeID` and `JobRole`.

In [ ]:
is_single = df['MaritalStatus'] == 'Single'
low_satisfaction = df['JobSatisfaction'] < 3
far_from_home = df['DistanceFromHome'] > 10

df_rd = is_single & low_satisfaction & far_from_home

df_rd = df[df_rd]

df_rd[['EmployeeID', 'JobRole']].head()


EmployeeID            JobRole
20        1021  Software Engineer
30        1031     Lab Technician
42        1043         HR Manager
43        1044         HR Manager
45        1046  Software Engineer